apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-soat-clientes-config
  namespace: fiap-soat-app
  labels:
    app: fiap-soat-clientes
    service: clientes
data:
  NODE_ENV: "production"
  PORT: "3000"
  
  # AWS Configuration
  AWS_REGION: "us-east-1"
  
  # Database Configuration (RDS Clientes)
  DATABASE_HOST: "fiap-soat-db-clientes.cjq57yoxrulq.us-east-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "fiapdb_clientes"
  DATABASE_USERNAME: "postgresadmin"
  DATABASE_SSL: "true"
